import './globals.css';
import { Inter } from 'next/font/google';
import Sidebar from './components/Sidebar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        {/* Top Fixed Bar */}
        <div style={{
          zIndex: 1,
          position: 'fixed',
          top: '0',
          backgroundColor: 'white',
          width: '100vw',
          height: '4rem'
        }}>
        </div>

        {/* LAYOUT for PAGE */}
        <div style={{
          marginTop: '2rem',
          display: 'grid',
          gridTemplateColumns: '1fr 3fr',
          height: 'calc(100vh - 4rem)'
        }}>

          {/* LAYOUT for Sidebar */}
          <div style={{
            position: 'fixed',
            left: '2.5vw',
            backgroundColor: 'white',
            width: '22.5vw',
          }}>
            <Sidebar />
          </div>

          {/* LAYOUT for Main Content */}
          <div style={{
            marginLeft: '25vw',
            backgroundColor: 'white',
            width: '72.5vw',
            borderLeft: '2rem white solid'
          }}>
            {children}
          </div>
        </div>

        {/* Bottom Fixed Bar */}
        <div style={{
          position: 'fixed',
          bottom: '0',
          backgroundColor: 'white',
          width: '100vw',
          height: '4rem'
        }}></div>
      </body>
    </html>
  )
}